//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTUforKidsService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int TestId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Difficulty { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> QuestionAmount { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
